import {
  ArchiveIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleHelpIcon,
  ClockIcon,
  CloseIcon,
  CopyIcon,
  DownloadIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileTextIcon,
  FilterIcon,
  FolderIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MenuIcon,
  MicIcon,
  MinusIcon,
  PauseIcon,
  PencilIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PrinterIcon,
  RefreshCwIcon,
  SaveIcon,
  SearchIcon,
  ShareIcon,
  StarIcon,
  TrashIcon,
  TriangleAlertIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  Volume2Icon,
  MoonIcon,
  SunIcon,
} from "./interface";

export type IconCategory = "Interface";

export type IconRegistryItem = {
  name: string;
  exportName: string;
  category: IconCategory;
  description: string;
  tags: readonly string[];
  Icon: typeof ArrowRightIcon;
};

export const iconRegistry = [
  { name: "Sun", exportName: "SunIcon", category: "Interface", description: "Sun icon.", tags: ["sun", "light", "theme", "day"], Icon: SunIcon },
  { name: "Moon", exportName: "MoonIcon", category: "Interface", description: "Moon icon.", tags: ["moon", "dark", "theme", "night"], Icon: MoonIcon },
  { name: "Archive", exportName: "ArchiveIcon", category: "Interface", description: "Archive icon.", tags: ["archive", "records"], Icon: ArchiveIcon },
  { name: "Arrow down", exportName: "ArrowDownIcon", category: "Interface", description: "Arrow down icon.", tags: ["arrow", "down", "navigation"], Icon: ArrowDownIcon },
  { name: "Arrow left", exportName: "ArrowLeftIcon", category: "Interface", description: "Arrow left icon.", tags: ["arrow", "left", "back"], Icon: ArrowLeftIcon },
  { name: "Arrow right", exportName: "ArrowRightIcon", category: "Interface", description: "Arrow right icon.", tags: ["arrow", "right", "next"], Icon: ArrowRightIcon },
  { name: "Arrow up", exportName: "ArrowUpIcon", category: "Interface", description: "Arrow up icon.", tags: ["arrow", "up", "navigation"], Icon: ArrowUpIcon },
  { name: "Arrow up down", exportName: "ArrowUpDownIcon", category: "Interface", description: "Arrow up down icon.", tags: ["sort", "order", "up", "down"], Icon: ArrowUpDownIcon },
  { name: "Bookmark", exportName: "BookmarkIcon", category: "Interface", description: "Bookmark icon.", tags: ["bookmark", "saved"], Icon: BookmarkIcon },
  { name: "Calendar", exportName: "CalendarIcon", category: "Interface", description: "Calendar icon.", tags: ["calendar", "date"], Icon: CalendarIcon },
  { name: "Camera", exportName: "CameraIcon", category: "Interface", description: "Camera icon.", tags: ["camera", "photo"], Icon: CameraIcon },
  { name: "Check", exportName: "CheckIcon", category: "Interface", description: "Check icon.", tags: ["check", "success", "complete"], Icon: CheckIcon },
  { name: "Chevron down", exportName: "ChevronDownIcon", category: "Interface", description: "Chevron down icon.", tags: ["chevron", "down", "expand"], Icon: ChevronDownIcon },
  { name: "Chevron left", exportName: "ChevronLeftIcon", category: "Interface", description: "Chevron left icon.", tags: ["chevron", "left", "previous"], Icon: ChevronLeftIcon },
  { name: "Chevron right", exportName: "ChevronRightIcon", category: "Interface", description: "Chevron right icon.", tags: ["chevron", "right", "next"], Icon: ChevronRightIcon },
  { name: "Chevron up", exportName: "ChevronUpIcon", category: "Interface", description: "Chevron up icon.", tags: ["chevron", "up", "collapse"], Icon: ChevronUpIcon },
  { name: "Clock", exportName: "ClockIcon", category: "Interface", description: "Clock icon.", tags: ["clock", "time"], Icon: ClockIcon },
  { name: "Close", exportName: "CloseIcon", category: "Interface", description: "Close icon.", tags: ["close", "x", "dismiss"], Icon: CloseIcon },
  { name: "Copy", exportName: "CopyIcon", category: "Interface", description: "Copy icon.", tags: ["copy", "clipboard"], Icon: CopyIcon },
  { name: "Download", exportName: "DownloadIcon", category: "Interface", description: "Download icon.", tags: ["download", "file"], Icon: DownloadIcon },
  { name: "Ellipsis", exportName: "EllipsisIcon", category: "Interface", description: "Ellipsis icon.", tags: ["more", "overflow", "actions"], Icon: EllipsisIcon },
  { name: "Ellipsis vertical", exportName: "EllipsisVerticalIcon", category: "Interface", description: "Ellipsis vertical icon.", tags: ["more", "overflow", "actions"], Icon: EllipsisVerticalIcon },
  { name: "Error", exportName: "CircleAlertIcon", category: "Interface", description: "Error icon.", tags: ["error", "alert"], Icon: CircleAlertIcon },
  { name: "External link", exportName: "ExternalLinkIcon", category: "Interface", description: "External link icon.", tags: ["external", "open"], Icon: ExternalLinkIcon },
  { name: "Eye", exportName: "EyeIcon", category: "Interface", description: "Eye icon.", tags: ["eye", "visibility", "view"], Icon: EyeIcon },
  { name: "Eye off", exportName: "EyeOffIcon", category: "Interface", description: "Eye off icon.", tags: ["eye", "hidden"], Icon: EyeOffIcon },
  { name: "File text", exportName: "FileTextIcon", category: "Interface", description: "File text icon.", tags: ["file", "document"], Icon: FileTextIcon },
  { name: "Filter", exportName: "FilterIcon", category: "Interface", description: "Filter icon.", tags: ["filter", "list"], Icon: FilterIcon },
  { name: "Folder", exportName: "FolderIcon", category: "Interface", description: "Folder icon.", tags: ["folder", "collection"], Icon: FolderIcon },
  { name: "Heart", exportName: "HeartIcon", category: "Interface", description: "Heart icon.", tags: ["heart", "favorite"], Icon: HeartIcon },
  { name: "Help", exportName: "CircleHelpIcon", category: "Interface", description: "Help icon.", tags: ["help", "question"], Icon: CircleHelpIcon },
  { name: "Home", exportName: "HomeIcon", category: "Interface", description: "Home icon.", tags: ["home", "dashboard"], Icon: HomeIcon },
  { name: "Image", exportName: "ImageIcon", category: "Interface", description: "Image icon.", tags: ["image", "photo"], Icon: ImageIcon },
  { name: "Info", exportName: "InfoIcon", category: "Interface", description: "Info icon.", tags: ["info", "details"], Icon: InfoIcon },
  { name: "Link", exportName: "LinkIcon", category: "Interface", description: "Link icon.", tags: ["link", "url"], Icon: LinkIcon },
  { name: "Lock", exportName: "LockIcon", category: "Interface", description: "Lock icon.", tags: ["lock", "secure"], Icon: LockIcon },
  { name: "Mail", exportName: "MailIcon", category: "Interface", description: "Mail icon.", tags: ["mail", "email"], Icon: MailIcon },
  { name: "Map pin", exportName: "MapPinIcon", category: "Interface", description: "Map pin icon.", tags: ["map", "location"], Icon: MapPinIcon },
  { name: "Menu", exportName: "MenuIcon", category: "Interface", description: "Menu icon.", tags: ["menu", "navigation"], Icon: MenuIcon },
  { name: "Mic", exportName: "MicIcon", category: "Interface", description: "Mic icon.", tags: ["mic", "audio"], Icon: MicIcon },
  { name: "Minus", exportName: "MinusIcon", category: "Interface", description: "Minus icon.", tags: ["minus", "remove", "collapse"], Icon: MinusIcon },
  { name: "Pause", exportName: "PauseIcon", category: "Interface", description: "Pause icon.", tags: ["pause", "media"], Icon: PauseIcon },
  { name: "Pencil", exportName: "PencilIcon", category: "Interface", description: "Pencil icon.", tags: ["edit", "write", "pencil"], Icon: PencilIcon },
  { name: "Phone", exportName: "PhoneIcon", category: "Interface", description: "Phone icon.", tags: ["phone", "call"], Icon: PhoneIcon },
  { name: "Play", exportName: "PlayIcon", category: "Interface", description: "Play icon.", tags: ["play", "media"], Icon: PlayIcon },
  { name: "Plus", exportName: "PlusIcon", category: "Interface", description: "Plus icon.", tags: ["plus", "add", "create"], Icon: PlusIcon },
  { name: "Printer", exportName: "PrinterIcon", category: "Interface", description: "Printer icon.", tags: ["print", "printer"], Icon: PrinterIcon },
  { name: "Refresh", exportName: "RefreshCwIcon", category: "Interface", description: "Refresh icon.", tags: ["refresh", "reload", "sync"], Icon: RefreshCwIcon },
  { name: "Save", exportName: "SaveIcon", category: "Interface", description: "Save icon.", tags: ["save", "store"], Icon: SaveIcon },
  { name: "Search", exportName: "SearchIcon", category: "Interface", description: "Search icon.", tags: ["search", "find", "query"], Icon: SearchIcon },
  { name: "Share", exportName: "ShareIcon", category: "Interface", description: "Share icon.", tags: ["share", "send"], Icon: ShareIcon },
  { name: "Star", exportName: "StarIcon", category: "Interface", description: "Star icon.", tags: ["star", "favorite"], Icon: StarIcon },
  { name: "Trash", exportName: "TrashIcon", category: "Interface", description: "Trash icon.", tags: ["delete", "remove", "trash"], Icon: TrashIcon },
  { name: "Unlock", exportName: "UnlockIcon", category: "Interface", description: "Unlock icon.", tags: ["unlock", "open"], Icon: UnlockIcon },
  { name: "Upload", exportName: "UploadIcon", category: "Interface", description: "Upload icon.", tags: ["upload", "file"], Icon: UploadIcon },
  { name: "User", exportName: "UserIcon", category: "Interface", description: "User icon.", tags: ["user", "person"], Icon: UserIcon },
  { name: "Users", exportName: "UsersIcon", category: "Interface", description: "Users icon.", tags: ["users", "group"], Icon: UsersIcon },
  { name: "Video", exportName: "VideoIcon", category: "Interface", description: "Video icon.", tags: ["video", "media"], Icon: VideoIcon },
  { name: "Volume", exportName: "Volume2Icon", category: "Interface", description: "Volume icon.", tags: ["volume", "audio"], Icon: Volume2Icon },
  { name: "Warning", exportName: "TriangleAlertIcon", category: "Interface", description: "Warning icon.", tags: ["warning", "alert"], Icon: TriangleAlertIcon },
] as const satisfies readonly IconRegistryItem[];

export const iconCategories = [
  "Interface",
] as const satisfies readonly IconCategory[];
