import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  BookmarkIcon,
  CameraIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleHelpIcon,
  CloseIcon,
  CopyIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  EyeIcon,
  EyeOffIcon,
  FileTextIcon,
  FolderIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  LinkIcon,
  LockIcon,
  MenuIcon,
  MicIcon,
  MinusIcon,
  PauseIcon,
  PencilIcon,
  PlayIcon,
  PlusIcon,
  PrinterIcon,
  RefreshCwIcon,
  SaveIcon,
  SearchIcon,
  ShareIcon,
  StarIcon,
  TrashIcon,
  TriangleAlertIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  Volume2Icon,
} from "./interface";

import {
  ChaliceIcon,
  ChurchIcon,
  CrossIcon,
} from "./catholic";

export type IconCategory =
  | "Interface"
  | "Catholic"
  | "Liturgy"
  | "Documents"
  | "Parish";

export type IconRegistryItem = {
  name: string;
  exportName: string;
  category: IconCategory;
  description: string;
  tags: readonly string[];
  Icon: typeof ArrowRightIcon;
};

export const iconRegistry = [
  { name: "Arrow left", exportName: "ArrowLeftIcon", category: "Interface", description: "Directional arrow for back navigation.", tags: ["arrow", "left", "back", "navigation"], Icon: ArrowLeftIcon },
  { name: "Arrow up", exportName: "ArrowUpIcon", category: "Interface", description: "Directional arrow for upward movement or sorting.", tags: ["arrow", "up", "sort", "navigation"], Icon: ArrowUpIcon },
  { name: "Arrow down", exportName: "ArrowDownIcon", category: "Interface", description: "Directional arrow for downward movement or sorting.", tags: ["arrow", "down", "sort", "navigation"], Icon: ArrowDownIcon },
  { name: "Chevron right", exportName: "ChevronRightIcon", category: "Interface", description: "Nested navigation, accordions, breadcrumbs, and disclosure controls.", tags: ["chevron", "right", "disclosure", "navigation"], Icon: ChevronRightIcon },
  { name: "Chevron left", exportName: "ChevronLeftIcon", category: "Interface", description: "Back navigation, previous controls, and disclosure controls.", tags: ["chevron", "left", "back", "navigation"], Icon: ChevronLeftIcon },
  { name: "Chevron up", exportName: "ChevronUpIcon", category: "Interface", description: "Collapse, close disclosure, or move upward.", tags: ["chevron", "up", "collapse", "disclosure"], Icon: ChevronUpIcon },
  { name: "Ellipsis", exportName: "EllipsisIcon", category: "Interface", description: "More actions, overflow menus, and compact controls.", tags: ["ellipsis", "more", "overflow", "actions"], Icon: EllipsisIcon },
  { name: "Ellipsis vertical", exportName: "EllipsisVerticalIcon", category: "Interface", description: "Vertical overflow menus and more actions.", tags: ["ellipsis", "vertical", "more", "overflow"], Icon: EllipsisVerticalIcon },
  { name: "Plus", exportName: "PlusIcon", category: "Interface", description: "Add, create, expand, or include an item.", tags: ["plus", "add", "create", "new"], Icon: PlusIcon },
  { name: "Minus", exportName: "MinusIcon", category: "Interface", description: "Remove, collapse, subtract, or minimize.", tags: ["minus", "remove", "collapse"], Icon: MinusIcon },
  { name: "Pencil", exportName: "PencilIcon", category: "Interface", description: "Edit, write, revise, or annotate content.", tags: ["pencil", "edit", "write", "annotate"], Icon: PencilIcon },
  { name: "Trash", exportName: "TrashIcon", category: "Interface", description: "Delete, remove, or discard content.", tags: ["trash", "delete", "remove"], Icon: TrashIcon },
  { name: "Upload", exportName: "UploadIcon", category: "Interface", description: "Upload documents, media, files, or records.", tags: ["upload", "file", "document", "media"], Icon: UploadIcon },
  { name: "Refresh clockwise", exportName: "RefreshCwIcon", category: "Interface", description: "Refresh data, reload content, or synchronize state.", tags: ["refresh", "reload", "sync"], Icon: RefreshCwIcon },
  { name: "Home", exportName: "HomeIcon", category: "Interface", description: "Home pages, dashboards, and primary navigation.", tags: ["home", "dashboard", "navigation"], Icon: HomeIcon },
  { name: "User", exportName: "UserIcon", category: "Interface", description: "Single person, account, profile, or contact.", tags: ["user", "person", "profile", "account"], Icon: UserIcon },
  { name: "Users", exportName: "UsersIcon", category: "Interface", description: "Groups, teams, families, members, or communities.", tags: ["users", "group", "team", "community"], Icon: UsersIcon },
  { name: "Lock", exportName: "LockIcon", category: "Interface", description: "Locked, private, protected, or secure content.", tags: ["lock", "private", "secure", "protected"], Icon: LockIcon },
  { name: "Unlock", exportName: "UnlockIcon", category: "Interface", description: "Unlocked, public, available, or open content.", tags: ["unlock", "open", "available"], Icon: UnlockIcon },
  { name: "Eye", exportName: "EyeIcon", category: "Interface", description: "Visibility, preview, read, or view action.", tags: ["eye", "visibility", "view", "preview"], Icon: EyeIcon },
  { name: "Eye off", exportName: "EyeOffIcon", category: "Interface", description: "Hidden, private, invisible, or disabled visibility.", tags: ["eye", "hidden", "visibility off", "private"], Icon: EyeOffIcon },
  { name: "Info", exportName: "InfoIcon", category: "Interface", description: "Information, notes, details, and help text.", tags: ["info", "information", "details", "note"], Icon: InfoIcon },
  { name: "Triangle alert", exportName: "TriangleAlertIcon", category: "Interface", description: "Warning, attention, caution, or important notice.", tags: ["warning", "alert", "caution"], Icon: TriangleAlertIcon },
  { name: "Circle alert", exportName: "CircleAlertIcon", category: "Interface", description: "Error, problem, validation failure, or urgent notice.", tags: ["error", "alert", "problem", "validation"], Icon: CircleAlertIcon },
  { name: "Circle help", exportName: "CircleHelpIcon", category: "Interface", description: "Help, questions, support, or guidance.", tags: ["help", "question", "support", "guidance"], Icon: CircleHelpIcon },
  { name: "Star", exportName: "StarIcon", category: "Interface", description: "Featured, favorite, rating, or important item.", tags: ["star", "favorite", "featured", "rating"], Icon: StarIcon },
  { name: "Heart", exportName: "HeartIcon", category: "Interface", description: "Favorite, care, devotion, or support.", tags: ["heart", "favorite", "care", "support"], Icon: HeartIcon },
  { name: "Bookmark", exportName: "BookmarkIcon", category: "Interface", description: "Saved items, bookmarks, or retained resources.", tags: ["bookmark", "save", "saved"], Icon: BookmarkIcon },
  { name: "Share", exportName: "ShareIcon", category: "Interface", description: "Share links, pages, files, or resources.", tags: ["share", "send", "distribute"], Icon: ShareIcon },
  { name: "Link", exportName: "LinkIcon", category: "Interface", description: "Links, references, anchors, and connections.", tags: ["link", "url", "reference", "anchor"], Icon: LinkIcon },
  { name: "Arrow up down", exportName: "ArrowUpDownIcon", category: "Interface", description: "Sorting, ordering, reordering, or bidirectional movement.", tags: ["sort", "order", "up", "down"], Icon: ArrowUpDownIcon },
  { name: "Image", exportName: "ImageIcon", category: "Interface", description: "Images, photos, media, and galleries.", tags: ["image", "photo", "media", "gallery"], Icon: ImageIcon },
  { name: "File text", exportName: "FileTextIcon", category: "Interface", description: "Documents, text files, bulletins, forms, and written records.", tags: ["file", "text", "document", "bulletin"], Icon: FileTextIcon },
  { name: "Folder", exportName: "FolderIcon", category: "Interface", description: "Folders, collections, archives, and grouped resources.", tags: ["folder", "collection", "archive"], Icon: FolderIcon },
  { name: "Printer", exportName: "PrinterIcon", category: "Interface", description: "Print pages, documents, forms, and bulletins.", tags: ["print", "printer", "document"], Icon: PrinterIcon },
  { name: "Save", exportName: "SaveIcon", category: "Interface", description: "Save, persist, store, or retain changes.", tags: ["save", "store", "persist"], Icon: SaveIcon },
  { name: "Camera", exportName: "CameraIcon", category: "Interface", description: "Photos, photography, images, and media capture.", tags: ["camera", "photo", "image", "media"], Icon: CameraIcon },
  { name: "Video", exportName: "VideoIcon", category: "Interface", description: "Video, livestreams, recordings, and media.", tags: ["video", "livestream", "recording", "media"], Icon: VideoIcon },
  { name: "Mic", exportName: "MicIcon", category: "Interface", description: "Audio, microphones, talks, recordings, and livestreams.", tags: ["mic", "audio", "recording", "talk"], Icon: MicIcon },
  { name: "Volume", exportName: "Volume2Icon", category: "Interface", description: "Audio, sound, volume, and media playback.", tags: ["volume", "audio", "sound"], Icon: Volume2Icon },
  { name: "Play", exportName: "PlayIcon", category: "Interface", description: "Play media, start video, or begin audio.", tags: ["play", "media", "video", "audio"], Icon: PlayIcon },
  { name: "Pause", exportName: "PauseIcon", category: "Interface", description: "Pause media, audio, video, or playback.", tags: ["pause", "media", "video", "audio"], Icon: PauseIcon },

  {
    name: "Arrow right",
    exportName: "ArrowRightIcon",
    category: "Interface",
    description: "Directional arrow for links, navigation, and calls to action.",
    tags: ["arrow", "right", "next", "cta", "navigation"],
    Icon: ArrowRightIcon,
  },
  {
    name: "Check",
    exportName: "CheckIcon",
    category: "Interface",
    description: "Confirmation, completion, or selected state.",
    tags: ["check", "success", "complete", "selected"],
    Icon: CheckIcon,
  },
  {
    name: "Close",
    exportName: "CloseIcon",
    category: "Interface",
    description: "Close, dismiss, or remove action.",
    tags: ["close", "dismiss", "remove", "x"],
    Icon: CloseIcon,
  },
  {
    name: "Copy",
    exportName: "CopyIcon",
    category: "Interface",
    description: "Copy code, text, links, or citations.",
    tags: ["copy", "clipboard", "code", "duplicate"],
    Icon: CopyIcon,
  },
  {
    name: "Chevron down",
    exportName: "ChevronDownIcon",
    category: "Interface",
    description: "Open menus, selects, accordions, and disclosure controls.",
    tags: ["chevron", "down", "select", "dropdown", "disclosure"],
    Icon: ChevronDownIcon,
  },
  {
    name: "Menu",
    exportName: "MenuIcon",
    category: "Interface",
    description: "Open navigation, drawers, or menus.",
    tags: ["menu", "hamburger", "navigation"],
    Icon: MenuIcon,
  },
  {
    name: "Search",
    exportName: "SearchIcon",
    category: "Interface",
    description: "Search documentation, archives, directories, or records.",
    tags: ["search", "find", "query", "archive"],
    Icon: SearchIcon,
  },
  {
    name: "Chalice",
    exportName: "ChaliceIcon",
    category: "Catholic",
    description: "Eucharistic chalice symbol for Mass, liturgy, and sacramental contexts.",
    tags: ["chalice", "mass", "eucharist", "liturgy", "sacrament"],
    Icon: ChaliceIcon,
  },
  {
    name: "Church",
    exportName: "ChurchIcon",
    category: "Catholic",
    description: "Church building symbol for parishes, dioceses, and locations.",
    tags: ["church", "parish", "diocese", "building", "location"],
    Icon: ChurchIcon,
  },
  {
    name: "Cross",
    exportName: "CrossIcon",
    category: "Catholic",
    description: "Primary Christian cross symbol.",
    tags: ["cross", "christian", "catholic", "faith"],
    Icon: CrossIcon,
  },
] as const satisfies readonly IconRegistryItem[];

export const iconCategories = [
  "Interface",
  "Catholic",
  "Liturgy",
  "Documents",
  "Parish",
] as const satisfies readonly IconCategory[];
